apiVersion: v1
kind: Pod
metadata:
  name: r-studio-pod-noauth
spec:
  containers:
    - name: r-studio
      image: rocker/rstudio
      env:
        - name: DISABLE_AUTH
          value: "true"
        - name: R_LIBS_USER
          value: /data
      ports:
        - containerPort: 8787
      volumeMounts:
        - name: hostpath-vol
          mountPath: /data
  volumes:
    - name: hostpath-vol
      persistentVolumeClaim:
        claimName: my-hostpath-pvc
